apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-aio-nextcloud-data
  name: nextcloud-aio-nextcloud-data
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  {{- if .Values.STORAGE_CLASS_DATA }}
  storageClassName: {{ .Values.STORAGE_CLASS_DATA }}
  {{- else if .Values.STORAGE_CLASS }}
  storageClassName: {{ .Values.STORAGE_CLASS }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.NEXTCLOUD_DATA_STORAGE_SIZE }}
